---
title: "Card game. N5"
output: pdf_document
lang: russian
---


У первого игрока 8 стратегий. Действительно, стратегия должна описывать, что делать, если пришла карта Ace, карта King, карта Queen, то есть стратегию можно записать тремя буквами. Например, RRF (raise, если пришла А; raise, если пришла K; fold, если пришла Q). У второго игрока две стратегии Pass и Call. Можно в принципе составить матрицу 8x2 и решить антагонистическую игру. 

Первому при хороших картах (Ace и Queen) выгодно делать Raise. Если сделать Fold, то это гарантированная потеря доллара, а если сделать Raise, то можно оказаться либо в плюсе, либо по нулям (в случае Queen). Вычеркиваем строго доминируемые стратегии и получаем матрицу 2x2.

В матрице ожидаемый выигрыш первого игрока:

 I/II | $(q)$ Pass   | $(1-q)$ Call
---- | ---    | --------
$(p)$ RRR  |  $1$   | $-m/3$
$(1-p)$ RFR  |  $1/3$ | $(m-1)/3$

Далее рассматриваем случаи. Немного громоздко, но однотипно.

Случай 1. $m>2$. Нет равновесий в чистых, есть единственное в смешанных.

Условие безразличия первого: $1q-m/3\cdot (1-q)=1/3\cdot q + (m-1)/3\cdot (1-q)$

Условие безразличия второго: $p+(1-p)/3=-pm/3+(1-p)(m-1)/3$

Находим $p=(m-2)/(2m+1)$, $q=(2m-1)/(2m+1)$

При $m\to\infty$ получаем $p\to 0.5$, $q\to 1$.

Случай 2. $1<m<2$. Есть равновесие в чистых, так как Call строго доминирует Pass.

Получаем равновесие RFR-Call. 

Случай 3. $m=2$. RFR-Call остается равновесием в чистых, но уже есть есть смешанные равновесия в окрестности.

При $m=2$: $p=0$, $q \leq 3/5$


  


