---
title: "Q5. 17 Dec 2014"
output: pdf_document
lang: russian
header-includes: 
  - \usepackage{tikz}
---

Q5. Не переворачиваем дерево. Для каждой стратегии второго игрока находим наилучшую стратегию первого:

lL -> DD 

lR -> UD 

rL -> DU 

rR -> UU

Найдём оптимальные ответы второго на действия первого:


UD -> rL

DU -> lR

DD -> lR или rR в зависимости от вер второго в верхнем инфо-множестве

UU -> lL или lR в зависимости от вер второго в нижнем инфо-множестве

Замечаем, что секвенциальных равновесий в чистых стратегиях нет. 

Будем искать смешанную поведенческую (mixed behavior) стратегию для каждого игрока.

Пусть второй использует стратегию $al+(1-a)r$ сверху и $bL+(1-b)R$ снизу.

Пусть первый использует стратегию $xU+(1-x)D$ слева и $yU+(1-y)D$ справа.


Веры второго сверху: $\mu_u$, $1-\mu_u$. Снизу: $\mu_d$, $1-\mu_d$.

Шаг 1. Сначала находим условие на веры, при которых второй может смешивать действия.

Второму безразлично как ходить сверху: $0\mu_u+1(1-\mu_u)=1\mu_u+0(1-\mu_u)$, $\mu_u=0.5$

Второму безразлично как ходить снизу: $0\mu_d+1(1-\mu_d)=6\mu_d+0(1-\mu_d)$, $\mu_d=1/7$

Шаг 2. Находим стратегии первого игрока, обеспечивающие такие веры. 

Будем пока что искать равновесия, где вероятность захода в каждое информационное множество строго больше нуля. В таком случае веры должны считаться по формуле условной вероятности (в знаменателе строго не ноль).

Чтобы обеспечить верхнее равенство вер (второму будет безразлично как ходить сверху): 

\[
\frac{x\cdot \frac{1}{3}}{y\cdot \frac{2}{3}}=\frac{0.5}{0.5}
\]

Или $2y=x$

Чтобы обеспечить нижнее равенство вер (второму будет безразлично как ходить снизу):

\[
\frac{(1-x)\cdot \frac{1}{3}}{(1-y)\cdot \frac{2}{3}}=\frac{1/7}{6/7}
\]

Или $3x-y=2$

Далее есть три варианта. Второй смешивает и сверху, и снизу. Второй смешивает сверху, но играет чистую снизу. Второй играет чистую сверху, но смешивает снизу. Заранее не ясно где повезет.

Рассматриваем вариант: второй смешивает и сверху, и снизу. Тогда оба условия на веры должны быть выполнены, получаем систему, находим, $x=4/5$, $y=2/5$.


Шаг 3. Второй уже ведёт себя оптимально и веры у него состоятельны, осталось добиться того, чтобы первому было оптимально использовать смешанную стратегию. Первый должен быть безразличен между чистыми.

Безразличие первого между U и D слева: $2a+1(1-a)=3b+0(1-b)$, $a=3b-1$

Безразличие первого между U и D слева: $0a+2(1-a)=1b+1(1-b)$, $a=1/2$.

Чтобы первому было безразлично везде, $a=1/2$, $b=1/2$.

Ура! $a=1/2$, $b=1/2$, $x=4/5$, $y=2/5$, $\mu_u=0.5$, $\mu_d=1/7$.


Примечание: теоретически нам могло бы не повезти, тогда пришлось бы перебирать случаи, где второй сверху или снизу не смешивает. Могло бы не повезти и в этих случаях, тогда пришлось бы пытаться искать особые равновесия, где первый чистую играет UU, а второй --- смесь lL и lR (не попадаем в нижнее инфо-множество), или где первый играет чистую DD, а второй смесь lR и rR (не попадаем в верхнее инфо-множество).


Тут для полноты матрица игры (для простоты записи домножена на три), но она не использовалась :)

I/II| lL  |  lR  |   rL  | rR  |
--- | --- | -----|-------|-----|
UU  | 2;2 | 2;2  |  5;1  | 5;1 |
UD  | 4;2 | 4;0  | 3;3   | 3;1 |
DU  | 3;2 |  0;8 |  7;0  | 4;6 |
DD  | 5;2 | 2;6  |  5;2  | 2;6 |
