---
title: "Q2. 17 Dec 2014"
output: pdf_document
lang: russian
header-includes: 
  - \usepackage{tikz}
---

Q2. 

1)

2) False. Верно, что не может быть меньше четырёх SPE (играть NE1 в первой партии и NE2 во второй партии, играть NE2 в первой и NE2 во второй партии и т.д.). Однако могут быть и другие SPE.  В SPE в любой подыгре, начинающейся со второго момента времени, должно быть сыграно равновесие Нэша. Следовательно, во второй партии (которая и есть подыгра) должно быть сыграно равновесие Нэша. В первой же партии может и не быть равновесия. Чтобы сыграть неравновесный исход в первой партии, один из игроков должен шантажировать второго в духе: "Если ты не сыграешь, как хочет моя левая нога, то во второй партии я подсуну тебе плохое для тебя равновесие Нэша!". 

Пример. Повторяется два раза базовая игра:

I/II| c       | d
--- | ---     | --------
a   |  (100;0)  | (-1;0)
b   |  (99;0) | (0;0)

Равновесий в базовой игре два: (a,c) и (b,d). Второму вообще пофиг как играть (поэтому любое его поведение оптимально), но в его власти лишить первого крупного выигрыша во второй партии. Соответственно, можно сконструировать такое SPE:

Стратегия 1-го: 

-  в первой партии играть b, 

-  во второй партии: играть a, если в первой был (b,с); иначе играть b

Стратегия 2-го:

-  в первой партии с,

-  во второй партии: играть c, если в первой был (b,с); иначе играть d

Проверяем, что это SPE. Во второй партии эти стратегии приводят к NE. В первой партии не NE, но (!) первая партия не есть подыгра (подыгра --- это от момента времени и далее до конца игры)! Может ли первый изменить свою стратегию в игре в целом и получить больше? Нет, т.к. изменение хода в первой партии лишает его 100 рублей во второй партии, давая лишь небольшой плюс в первой партии. 


здесь попутно мы решим Q3. В вопросе Q3 как раз нужно доказать, что если равновесие в базовой игре единственно ($a^{\circ}$), то при конечном повторении игры описанная выше ситуация шантажа не сложится. То есть нужно доказать, что в SPE стратегии игроков в любой момент времени будут говорить им ходить ход, соответствующий равновесию Нэша в базовой игре. 

Начинаем с конца. Последняя партия является подыгрой, поэтому в последней партии должно играться равновесие Нэша $a^{\circ}$. Но оно единственно, значит вне зависимости от предыстории в SPE стратегия игрока $i$ советует ему делать ход $a_i^{\circ}$ в последней партии. 

Переходим к предпоследней партии. В SPE выигрыш в последней партии, как мы уже знаем, не зависит от исхода предпоследней партии. Значит ничто далее не может компенсировать игроку неоптимальный ход в предпоследней партии. Значит в предпоследней партии должно играться равновесие Нэша $a_i^{\circ}$.

И так далее. 


3) False

Рассмотрим такой пример игры справа:

I/II| c       | d
--- | ---     | --------
a   |  (1;0)  | (0;1)
b   |  (0;1) | (1;0)

В ней единственное NE ($0.5a+0.5b$, $0.5c+0.5d$), игроки в среднем получают по $0.5$. И предположим, что веточка "налево" даёт обоим игрокам по $0.6$. 

Если мы ищем SPE, то справа получаем в матрице должен играться NE, то есть игроки получают по $0.5$ и первый выбирает на первом шаге $0.6$. 

Если же мы ищем NE в чистых. Вне зависимости от стратегии второго (c или d) первый может войти в игру и получить рубль.