---
title: "Q4. 17 Dec 2014"
output: pdf_document
lang: russian
header-includes: 
  - \usepackage{tikz}
---

Q4. У первого игрока $m_1$ доступных действий, обозначенных множеством $\bar{A}_1$. У второго игрока $m_2$ доступных действий, обозначенных множеством $\bar{A}_2$. 

1. Если игроки ходят одновременно, то у первого игрока $m_1$ стратегий, у второго игрока --- $m_2$ стратегий.

2. Если сначала ходит первый игрок, а второй --- после первого и видит его выбор $a_1$, то у первого игрока $m_1$ стратегий, а у второго --- $m_2^{m_1}$ стратегий. Стратегия второго игрока должна говорить ему, что делать при каждом выборе первого игрока, у первого игрока $m_1$ вариантов выбора, значит можно для удобства считать, что стратегия второго игрока --- это слово в котором $m_1$ букв, а для каждой буквы есть $m_2$ вариантов.

3. В двухшаговой игре стратегия второго игрока предписывает ему, что делать в зависимости от хода первого игрока. Про платежи известно, что при $a_2\neq a_2'$ оказывается, что $u_2(a_1, a_2)\neq u_2(a_1, a_2')$. Это означает, что на каждое действие $a_1$ первого игрока у второго игрока есть единственный наилучший ответ (из нескольких разных чисел всегда можно выбрать ровно одно наибольшее). Следовательно, в любом равновесии совершенном в подыграх (SPE) стратегия второго игрока одна и та же. Эта оптимальная стратегия, в частности, в ответ на ход $a_1^*$ предписывает второму выбирать $a_2^*$.  Итак, стратегия второго игрока фиксирована. Если первый пойдёт $a_1^*$, он получит выигрыш $\pi_1$. Раз есть ход, котором первый может гарантировать себе выигрыш $\pi_1$, то меньшим его выигрыш быть в равновесии не может.

4. Пример игры, где первый в двухшаговой игре в SPE получает меньше, чем в статической в NE:

Статическая:

I/II| c       | d
--- | ---     | --------
a   |  (1;0)  | (0;1)
b   |  (-1;0) | (1;0)


В статической игре --- единственное равновесие NE --- это (b,d), дающее первому игроку выигрыш $\pi_1=1$.

Если же эта игра, является двухшаговой (второй ходит после первого, зная его ход), то можно найти два SPE: (a-dc) и (b-dd). В (a-dc) первый получает 0, то есть меньше, чем в равновесии Нэша в статической игре.

\tikzset{
% Two node styles for game trees: solid and hollow
solid node/.style={circle,draw,inner sep=1.5,fill=black},
hollow node/.style={circle,draw,inner sep=1.5}
}
\begin{tikzpicture}[scale=1,font=\footnotesize]
% Specify spacing for each level of the tree
\tikzstyle{level 1}=[level distance=15mm,sibling distance=35mm]
\tikzstyle{level 2}=[level distance=15mm,sibling distance=15mm]
% The Tree
\node(0)[solid node,label=above:{$Player 1$}]{}
child{node(1)[solid node]{}
child{node[hollow node,label=below:{$(1,0)$}]{} edge from parent node[left]{$c$}}
child{node[hollow node,label=below:{$(0,1)$}]{} edge from parent node[right]{$d$}}
edge from parent node[left,xshift=-3]{$a$}
}
child{node(2)[solid node]{}
child{node[hollow node,label=below:{$(-1,0)$}]{} edge from parent node[left]{$c$}}
child{node[hollow node,label=below:{$(1,0)$}]{} edge from parent node[right]{$d$}}
edge from parent node[right,xshift=3]{$b$}
};
\end{tikzpicture}
