---
title: "Silverman’s game"
output: pdf_document
lang: russian
---


Для начала суть простыми словами. Игроки одновременно называют натуральные числа. Выигрывает тот, кто назовёт больше противника, но не слишком сильно больше. Точнее, игрок i выигрывает 1 рубль у игрока j, если $x_i$ попадает в интервал $(x_j, 3x_j)$. Если назвали одинаковые числа, то по нулям.

Равновесия в чистых стратегиях нет. Если один игрок назвал число a, то другой хочет назвать чуть больше чем "а", но тогда и первый хотел бы назвать чуть больше, чем второй, а не "а".

Ищем равновесие в смешанных. Если решать задачу с нуля и полностью, то она довольно громоздкая. Однако нам нужно найти хотя бы одно равновесие (an equilibrium). Теоретически в подобной игре может вообще не быть равновесия (даже в смешанных), так как множество стратегий не компактно.  Например в игре "у кого натуральное число больше" нет равновесия. 

Однако допустим, что здесь есть равновесие. В силу одинаковости игроков следует, что в равновесии ожидаемый выигрыш игроков равен нулю. Попробуем угадать какое-нибудь простое равновесие в смешанных. Попробуем самое простое распределение --- равновероятное. То есть мы ищем равновесие в котором оба игрока равновероятно выбирают числа $a_1$, $a_2$, ..., $a_k$.

В смешанном равновесии игрок безразличен между чистыми стратегиями. Значит первому всё равно на что ставить, любое из чисел $a_1$, $a_2$, ..., $a_k$ приносит ему в среднем ноль. 

Так как ставка на $a_1$ должна приносить ноль, значит среди оставшихся чисел одинаковое количество тех, что чуть больше $a_1$, и тех, что сильно больше $a_1$. Попробуем самый простой вариант: 1 число чуть больше $a_1$ и 1 число сильно больше $a_1$. 

Чтобы почувствовать игру, попробуем $a_1=1$. У нас "сильно больше" означает больше ровно в три раза или больше чем в три раза больше. Значит единственный шанс, чтобы $a_2$ было "чуть больше", это $a_2=2$.
Пробуем несколько a_3. Например, проверим на равновесность исход, в котором оба игрока равновероятно играют 1-2-3. Это не равносие, так как если один ставит на 1-2-3, то второму лучше вместо 3 выбирать 4 (4 выиграет у двойки и тройки, но проигрывает единице, а у нас должен быть баланс выигрышей и проигрышей и одна ничья для нулевых платежей).

Аналогично пробуем  1-2-4. Аналогично оказывается не равновесие, вместо 4 лучше называть 5 (5 выигрывает у двойки и четверки и проигрывает 1).

Аналогично пробуем 1-2-5. Бинго! 1 проигрывает двойке, но выигрывает у пятёрки. 2 выигрывает у 1, но проигрывает пятерке. 5 выигрывает у двойки, но проигрывает единице. Равновесие Нэша: называть 1-2-5 равновероятно (каждому игроку).

Игра известная, по ней написаны толстые книжки. Можно доказать, что это единственное равновесие в этой игре, но это уже не так легко.


