---
title: "Licence auction"
output: pdf_document
lang: russian
---

Предположим, что в равновесии фирмы-новички делают ставки согласно убывающей функции $b(c)$.

Тогда во второй раунд выйдет фирма с минимальными издержками $c=\min\{c_1,c_2\}$. Это всё, что знает фирма-старожил, поэтому с её точки зрения закон распределения издержек входящей фирмы --- это распределение минимума. Функция распределения минимума, 
\[
F_{c}(t)=P(c\leq t)=1-P(c>t)=1-P(c_1>t)P(c_2>t)=1-(\bar{c}-t)^2/\bar{c}^2
\]

Заметим, что $E(c)=\bar{c}/3$.

Во втором раунде фирма-старожил максимизирует свою ожидаемую прибыль производит количество $q_{old}$, а фирма новичок использует $q_{new}(c)$. 


Задача фирмы-новичка:

\[
\max_{q_{new}} q_{new}\cdot (1-q_{new}-q_{old}-c)
\]

Получаем функцию реакции: $q_{new}=(1-q_{old}-c)/2$.


Задача фирмы-старожила:

\[
\max_{q_{old}} E(q_{old}\cdot (1-q_{new}-q_{old}))
\]

С точки зрения фирмы-старожила случайными величинами являются $q_{new}$ и $c$. Отсюда:

\[
q_{old}=(1-E(q_{new}))/2
\]

Решая систему
\[
\begin{cases}
q_{new}=(1-q_{old}-c)/2 \\
q_{old}=(1-E(q_{new}))/2 \\
\end{cases}
\]

Находим: $q_{old}=\frac{1}{3}+E(c)$, $q_{new}=\frac{1}{3}-E(c)/2-c/2$

Замечаем, что при любых $c<1/2$, выпуск (и прибыль) фирмы новичка положительны. 

При условии, что $E(c)=\bar{c}/3$, получаем 
<!--$q_{old}=\frac{1+\bar{c}}{3}$, $q_{new}(c)=\frac{2-\bar{c}-3c}{6}$--> 
$q_{old}=\frac{3+\bar{c}}{9}$, $q_{new}(c)=\frac{6-\bar{c}-9c}{18}$.

И прибыль фирмы-новичка равна:

\[
\pi_{new}=q_{new}^2=(6-\bar{c}-9c)^2/18^2
\]

Но на аукционе второй цены игроку выгодно делать ставку равную своему выигрышу, то есть 

\[
b(c)=(6-\bar{c}-9c)^2/18^2
\]

Замечаем, что эта функция убывает, как мы и предполагали.
