---
title: "Marriage"
author: "xxx"
date: "11 March 2015"
output: pdf_document
lang: russian
---

Пусть $N$ --- случайная величина, равная номеру раунда, в котором происходит первая разнополая встреча для данного индивида.

Тогда ожидаемое значение дисконта между разнополыми встречами равно 
\[
E(\delta^N)=\delta \cdot \frac{1}{2} + \delta^2 \cdot \frac{1}{4} + ...=\frac{\delta}{2-\delta}=\triangle
\]

Далее будем рассматривать задачу с дисконтом $\triangle$, где по смыслу $\triangle$ --- это дисконт от одной разнополой встречи до другой.



Предположим, что в любом равновесии, совершенном в подыграх:

* $m$ --- выигрыш мужчины в подыгре, начинающейся с его предложения
* $f$ --- выигрыш женщины в подыгре, начинающейся с её предложения

Тогда:

* $\left( \frac{1}{4}f + \frac{3}{4}(1-m) \right)$ --- величина, которую получает женщина в подыгре, начинающейся с их встречи.

* $\left( \frac{1}{4}(1-f) + \frac{3}{4}m \right)$ --- величина, которую получает мужчина в подыгре, начинающейся с их встречи.

Условие согласия женщины на предложение:

\[
1-m\geq \triangle 
\left( \frac{1}{4}f + \frac{3}{4}(1-m) \right)
\]

Условие согласия мужчины на предложение:
\[
1-f\geq \triangle
\left( \frac{1}{4}(1-f) + \frac{3}{4}m \right)
\]

Составляем систему

\[
\begin{cases}
1-m=\triangle 
\left( \frac{1}{4}f + \frac{3}{4}(1-m) \right) \\
1-f=\triangle 
\left( \frac{1}{4}(1-f) + \frac{3}{4}m \right)
\end{cases}
\]


Решая эту систему находим, что $m=1-\frac{\triangle}{4}$, $f=1-\frac{3\triangle}{4}$.

Отсюда равновесные стратегии:

Мужчины:

Предлагать делёж $(u_m,u_f)=(1-\frac{\triangle}{4},\frac{\triangle}{4})$; соглашаться, если мне дают больше либо равно $\frac{3\triangle}{4}$. 

Женщины:

Предлагать делёж $(u_m,u_f)=(\frac{3\triangle}{4},1-\frac{3\triangle}{4})$; соглашаться, если мне дают больше либо равно $\frac{\triangle}{4}$. 





